title: "<p align=\"center\"> Satyam Chatrola </p>"

logo: "/images/satyam_headshot.png?raw=true"

url: "https://nightshade14.github.io"
baseurl: "/satyamchatrola"
repository: "Nightshade14/satyamchatrola"


description:
  <p align="center">
    <a href="pdf/Satyam Chandrakant Chatrola Resume.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/satyamchatrola">LinkedIn</a> |
    <a href="https://www.github.com/Nightshade14">GitHub</a> |
    <a href="https://www.kaggle.com/satyamchatrola">Kaggle</a> |
    <a href="https://cloudskillsboost.google/public_profiles/8f8d70ce-809c-45e2-b6ba-022e3bc4cf9f">Google Cloud Profile</a>
  </p>
  <p align="justify">
    Hello! I am Satyam Chatrola. I am a Machine Learning Engineer and a MS in CS student at New York University (NYU). I am passionate about building AI-based systems to drive innovation and solve complex problems. I leverage the principles of Software Engineering and combine them with Machine Learning Solutions and MLOps principles (with CI/CD) to deliver efficient, scalable and robust End to End AI Solution.
    <br><br>
    As a Data Scientist (with 1.5+ year of experience), I have worked on AI-powered Recommendation and Search System and have delivered dependable solutions driving business growth. I led the development of an AI-based Face Recognition, Productivity System and have collaborated with cross-functional teams and stakeholders to productionize the system. <br> 
  </p>


remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Permalinks
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/